[package]
name = "rOS"
version = "0.1.1"
edition = "2021"
authors = ["Radosław Wolański <radekw8733@gmail.com>"]

[features]
default = ["bootimage"]
bootimage = []
bootboot = []
font_embed = []

[profile.dev]
panic = "abort"
opt-level = 0

[profile.release]
panic = "abort"

[dependencies]
bootloader = "0.9.23"
spin = "0.9.8"
x86 = "*"
numtoa = "*"
pc-keyboard = "*"
linked_list_allocator = "*"

[dependencies.lazy_static]
features = ["spin_no_std"]

[dependencies.x86_64]
features = ["abi_x86_interrupt"]