[build]
target = "platform/x86_64/x86_64-unknown-none.json"
# target = "aarch64-unknown-none"


[target.'cfg(target_os = "linux")']
rustflags = ["-C", "link-arg=-nostartfiles"]

[target.'cfg(target_os = "windows")']
rustflags = ["-C", "link-args=/ENTRY:_start /SUBSYSTEM:console"]

[target.'cfg(target_os = "macos")']
rustflags = ["-C", "link-args=-e __start -static -nostartfiles"]

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[target.aarch64-unknown-none]
rustflags = ["-Clink-args=platform/aarch64/rpi4/link.ld"]